### ISSUE TITLE
Admin: User list page need to hide  if the user is admin.

### ISSUE THREAD

**Issue by mkandanmk7** [mythily-muthu/React-Ecommerce-client#1]
Actual Result : Its shows all the user  detail in table
![image (2)](https://user-images.githubusercontent.com/84056393/236658828-22cfbbd7-874c-402d-baca-2c73b5186e34.png)

Expected Result : hide if the user is admin.

**Comment by mythily-muthu** [comment]
delete button removed for admin
![image](https://user-images.githubusercontent.com/113460532/236667469-71dc4864-4fdd-47d2-ab34-8bf994cb9bab.png)

**Comment by mkandanmk7** [comment]
issue fixed.
![screenshot-mythu-ecommerce-app netlify app-2023 05 07-14_45_47](https://user-images.githubusercontent.com/84056393/236668916-bdfa640b-3d60-4828-a0e3-2859940922c3.png)
