### ISSUE TITLE
Admin: Add product page =>  Unable to create a product

### ISSUE THREAD

**Issue by mkandanmk7** [mythily-muthu/React-Ecommerce-client#2]
Actual result: while clicking add button , it does not work
![image (3)](https://user-images.githubusercontent.com/84056393/236659157-0580ad42-03ce-4f12-b61f-5b1916bded0c.png)

Expected result: If I click add button the product should be added in the **product list**

**Comment by mythily-muthu** [comment]
Fixed, Now the user can add new product

**Comment by mkandanmk7** [comment]
Fixed.
