### ISSUE TITLE
Admin Navbar => Need to show content properly

### ISSUE THREAD

**Issue by mkandanmk7** [mythily-muthu/React-Ecommerce-client#4]
![image](https://user-images.githubusercontent.com/84056393/236678097-579fa205-0710-4da5-a8ec-08f5126c1885.png)

**Comment by mythily-muthu** [comment]
Fixed
![image](https://user-images.githubusercontent.com/113460532/236683218-74428945-8519-4054-9b05-39b10ac3d342.png)

**Comment by mkandanmk7** [comment]
Fixed.
