### ISSUE TITLE
Admin Home page => Need to add proper padding

### ISSUE THREAD

**Issue by mkandanmk7** [mythily-muthu/React-Ecommerce-client#5]
![screenshot-mythu-ecommerce-app netlify app-2023 05 07-18_09_13](https://user-images.githubusercontent.com/84056393/236678262-19c0fd7d-b102-4732-9a20-e406a396d9c8.png)

**Comment by mythily-muthu** [comment]
fixed 
![image](https://user-images.githubusercontent.com/113460532/236682998-e6807d17-ec29-4b20-9620-77bf648e9061.png)

**Comment by mkandanmk7** [comment]
Fixed.
