### ISSUE TITLE
Admin: Product edit page: unable to Edit 

### ISSUE THREAD

**Issue by mkandanmk7** [mythily-muthu/React-Ecommerce-client#7]
Actual Result:  blank page shown,
Expected Result:  Product details should be editable.

**Comment by mythily-muthu** [comment]
fixed
![image](https://user-images.githubusercontent.com/113460532/236682742-e32127be-288e-4adc-9843-50f014659e92.png)

**Comment by mkandanmk7** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/84056393/236683705-85180d54-a516-46ec-b806-09d5ca3b0598.png)
